CONNECTALDIR?=../..
S2H_INTERFACES = MemwriteRequest:Memwrite.request
H2S_INTERFACES = Memwrite\#\(\`NumberOfMasters\):MemwriteIndication
MEM_WRITE_INTERFACES = lMemwrite.dmaClients

BSVFILES = Memwrite.bsv
CPPFILES = ../memwrite/testmemwrite.cpp
PLATFORM_NUMBER_OF_MASTERS =4

include $(CONNECTALDIR)/Makefile.connectal
