
INTERFACES = MemwriteRequest MemwriteIndication
BSVFILES = Memwrite.bsv Top.bsv
CPPFILES=testmemwrite.cpp
NUMBER_OF_MASTERS =4
#CONNECTALFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.connectal

