
CONNECTALDIR?=../..
S2H_INTERFACES = MemwriteRequest:Memwrite.request
H2S_INTERFACES = Memwrite\#\(\`NumberOfMasters\):MemwriteIndication
MEM_INTERFACES = nil,lMemwrite.dmaClients
BSVFILES = Memwrite.bsv
CPPFILES=../memwrite/testmemwrite.cpp

NUMBER_OF_MASTERS =4

include $(CONNECTALDIR)/Makefile.connectal

