CONNECTALDIR?=../..
S2H_INTERFACES = EchoRequest:Echo.request
H2S_INTERFACES = Echo:EchoIndication

BSVFILES = ../echo/Echo.bsv
CPPFILES= ../echo/testecho.cpp
NUMBER_OF_MASTERS =0

MAIN_CLOCK_PERIOD=20

include $(CONNECTALDIR)/Makefile.connectal

