
S2H = SmithwatermanRequest
H2S = SmithwatermanIndication
BSVFILES = Smithwaterman.bsv Top.bsv ../../lib/deprecated/DmaUtils.bsv
CPPFILES=testsmithwaterman.cpp
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.connectal
