
BSVDIR=../../bsv
S2H = SmithwatermanRequest DmaConfig
H2S = SmithwatermanIndication DmaIndication
BSVFILES = Smithwaterman.bsv Top.bsv
CPPFILES=testsmithwaterman.cpp
Dma = Dma
PINS = Std
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
