
S2H = NandSimRequest StrstrRequest
H2S = NandSimIndication StrstrIndication
BSVFILES = ../nandsim/NandSim.bsv ../strstr/Strstr.bsv Top.bsv ../nandsim/NandSimNames.bsv
CPPFILES=test.cpp

include ../../Makefile.xbsv
