
S2H = MemcpyRequest DmaConfig
H2S = MemcpyIndication DmaIndication
BSVFILES = Memcpy.bsv Top.bsv
CPPFILES=testmemcpy.cpp
Dma = Dma
PINS = Std
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
