CONNECTALDIR?=../..
S2H_INTERFACES = SimmRequest:Simm.request
H2S_INTERFACES = Simm:SimmIndication

BSVFILES = Simm.bsv
CPPFILES= test.cpp
CONNECTALFLAGS += -lpapi

include $(CONNECTALDIR)/Makefile.connectal
