CONNECTALDIR?=../..
INTERFACES = SignalGenRequest SignalGenIndication \
	BlueScopeEventPIORequest BlueScopeEventPIOIndication
BSVFILES = ../../lib/bsv/BlueScopeEventPIO.bsv SignalGen.bsv Top.bsv
CPPFILES=testbluescopeeventpio.cpp
NUMBER_OF_MASTERS =0

include $(CONNECTALDIR)/Makefile.connectal
