
S2H = MemcpyRequest DmaConfig
H2S = MemcpyIndication DmaIndication
BSVFILES = ../../lib/bsv/MemcpyEngine.bsv Memcpy.bsv Top.bsv
CPPFILES=testmemcpy.cpp
Dma = Dma
PINS = Std

include ../../Makefile.common
