CONNECTALDIR?=../..
S2H_INTERFACES = MemcpyRequest:Memcpy.request
H2S_INTERFACES = Memcpy:MemcpyIndication
MEM_READ_INTERFACES = lMemcpy.dmaReadClient
MEM_WRITE_INTERFACES = lMemcpy.dmaWriteClient

BSVFILES = ../memcpy/Memcpy.bsv
CPPFILES=  ../memcpy/testmemcpy.cpp

include $(CONNECTALDIR)/Makefile.connectal
