#-----------------------------------------------------------
# Vivado v2016.2 (64-bit)
# SW Build 1577090 on Thu Jun  2 16:32:35 MDT 2016
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016
# Start of session at: Tue Aug 16 11:26:40 2016
# Process ID: 16256
# Current directory: /home/jamey/connectal/tests/nvme_strstr/miniitx100
# Command line: vivado
# Log file: /home/jamey/connectal/tests/nvme_strstr/miniitx100/vivado.log
# Journal file: /home/jamey/connectal/tests/nvme_strstr/miniitx100/vivado.jou
#-----------------------------------------------------------
file delete -force -- nvmecore
create_project nvmecore nvmecore -part xc7z100ffg900-2
#set_property board_part xilinx.com:zc706:part0:1.3 [current_project]
add_files ../miniitx100/verilog
add_files -norecurse ../cores/miniitx100/axi_pcie_rp/axi_pcie_rp.xci
export_ip_user_files -of_objects  [get_files  /home/jamey/connectal/tests/nvme_strstr/cores/miniitx100/axi_pcie_rp/axi_pcie_rp.xci] -force -quiet
update_compile_order -fileset sources_1
update_compile_order -fileset sim_1
update_compile_order -fileset sources_1
ipx::package_project -root_dir . -vendor user.org -library user -taxonomy /UserIP
set_property library {} [ipx::current_core]
set_property vendor accelerated.tech [ipx::current_core]
set_property library user [ipx::current_core]
set_property name nvme100 [ipx::current_core]
set_property display_name nvme100 [ipx::current_core]
set_property description {nvme for avnet mini-itx 100} [ipx::current_core]
ipx::add_bus_interface ddr3 [ipx::current_core]
set_property abstraction_type_vlnv xilinx.com:interface:ddrx_rtl:1.0 [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property bus_type_vlnv xilinx.com:interface:ddrx:1.0 [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
ipx::add_port_map CS_N [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_CS_n [ipx::get_port_maps CS_N -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map CK_P [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_Clk_p [ipx::get_port_maps CK_P -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map CK_N [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_Clk_n [ipx::get_port_maps CK_N -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map DM [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_DM [ipx::get_port_maps DM -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map CAS_N [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_CAS_n [ipx::get_port_maps CAS_N -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map DQ [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_DQ [ipx::get_port_maps DQ -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map ADDR [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_Addr [ipx::get_port_maps ADDR -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map RAS_N [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_RAS_n [ipx::get_port_maps RAS_N -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map RESET_N [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_DRSTB [ipx::get_port_maps RESET_N -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map DQS_N [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_DQS_n [ipx::get_port_maps DQS_N -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map DQS_P [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_DQS_p [ipx::get_port_maps DQS_P -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map WE_N [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_WEB [ipx::get_port_maps WE_N -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map CKE [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_CKE [ipx::get_port_maps CKE -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map ODT [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_ODT [ipx::get_port_maps ODT -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_port_map BA [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]
set_property physical_name DDR_BankAddr [ipx::get_port_maps BA -of_objects [ipx::get_bus_interfaces ddr3 -of_objects [ipx::current_core]]]
ipx::add_bus_interface pcie_mgt [ipx::current_core]
set_property abstraction_type_vlnv xilinx.com:interface:pcie_7x_mgt_rtl:1.0 [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]
set_property bus_type_vlnv xilinx.com:interface:pcie_7x_mgt:1.0 [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]
ipx::add_port_map rxn [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]
set_property physical_name pcie_exp_rxn_v [ipx::get_port_maps rxn -of_objects [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]]
ipx::add_port_map txn [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]
set_property physical_name pcie_exp_txn [ipx::get_port_maps txn -of_objects [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]]
ipx::add_port_map rxp [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]
set_property physical_name pcie_exp_rxp_v [ipx::get_port_maps rxp -of_objects [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]]
ipx::add_port_map txp [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]
set_property physical_name pcie_exp_txp [ipx::get_port_maps txp -of_objects [ipx::get_bus_interfaces pcie_mgt -of_objects [ipx::current_core]]]
ipx::add_bus_interface pcie_refclk [ipx::current_core]
set_property abstraction_type_vlnv xilinx.com:interface:diff_clock_rtl:1.0 [ipx::get_bus_interfaces pcie_refclk -of_objects [ipx::current_core]]
set_property bus_type_vlnv xilinx.com:interface:diff_clock:1.0 [ipx::get_bus_interfaces pcie_refclk -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces pcie_refclk -of_objects [ipx::current_core]]
set_property interface_mode slave [ipx::get_bus_interfaces pcie_refclk -of_objects [ipx::current_core]]
ipx::add_port_map CLK_P [ipx::get_bus_interfaces pcie_refclk -of_objects [ipx::current_core]]
set_property physical_name pcie_refclk_p [ipx::get_port_maps CLK_P -of_objects [ipx::get_bus_interfaces pcie_refclk -of_objects [ipx::current_core]]]
ipx::add_port_map CLK_N [ipx::get_bus_interfaces pcie_refclk -of_objects [ipx::current_core]]
set_property physical_name pcie_refclk_n [ipx::get_port_maps CLK_N -of_objects [ipx::get_bus_interfaces pcie_refclk -of_objects [ipx::current_core]]]
ipx::remove_bus_interface CLK_deleteme_unused_clock [ipx::current_core]
ipx::remove_bus_interface CLK_GATE_deleteme_unused_clock [ipx::current_core]
ipx::remove_port CLK_deleteme_unused_clock [ipx::current_core]
ipx::remove_port CLK_GATE_deleteme_unused_clock [ipx::current_core]
ipx::remove_port CLK_deleteme_unused_clock_0 [ipx::current_core]
ipx::remove_port CLK_GATE_deleteme_unused_clock_0 [ipx::current_core]
ipx::remove_port CLK_deleteme_unused_clock_1 [ipx::current_core]
ipx::remove_port CLK_GATE_deleteme_unused_clock_1 [ipx::current_core]
ipx::remove_port CLK_deleteme_unused_clock_2 [ipx::current_core]
ipx::remove_port CLK_GATE_deleteme_unused_clock_2 [ipx::current_core]
ipx::remove_port CLK_deleteme_unused_clock_3 [ipx::current_core]
ipx::remove_port CLK_GATE_deleteme_unused_clock_3 [ipx::current_core]
ipx::remove_port RST_N_deleteme_unused_reset_0 [ipx::current_core]
ipx::remove_port RST_N_deleteme_unused_reset_1 [ipx::current_core]
ipx::remove_port RST_N_deleteme_unused_reset_2 [ipx::current_core]
ipx::remove_port RST_N_deleteme_unused_reset_3 [ipx::current_core]
ipx::associate_bus_interfaces -busif ddr3 -clock DDR_Clk_p [ipx::current_core]
ipx::associate_bus_interfaces -busif ddr3 -clock DDR_Clk_n [ipx::current_core]
ipx::remove_bus_interface CLK [ipx::current_core]
ipx::remove_port CLK [ipx::current_core]
ipx::remove_port RST_N [ipx::current_core]
ipx::add_bus_interface pcie_sys_reset_n [ipx::current_core]
set_property abstraction_type_vlnv xilinx.com:signal:reset_rtl:1.0 [ipx::get_bus_interfaces pcie_sys_reset_n -of_objects [ipx::current_core]]
set_property bus_type_vlnv xilinx.com:signal:reset:1.0 [ipx::get_bus_interfaces pcie_sys_reset_n -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces pcie_sys_reset_n -of_objects [ipx::current_core]]
set_property interface_mode slave [ipx::get_bus_interfaces pcie_sys_reset_n -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces pcie_sys_reset_n -of_objects [ipx::current_core]]
ipx::add_port_map RST [ipx::get_bus_interfaces pcie_sys_reset_n -of_objects [ipx::current_core]]
set_property physical_name RST_N_pcie_sys_reset_n [ipx::get_port_maps RST -of_objects [ipx::get_bus_interfaces pcie_sys_reset_n -of_objects [ipx::current_core]]]
ipx::infer_bus_interface FIXED_IO_ddr_vrn xilinx.com:signal:data_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {FIXED_IO_ddr_vrp MIO FIXED_IO_ps_porb FIXED_IO_ps_srstb} xilinx.com:signal:data_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface FIXED_IO_ddr_vrp xilinx.com:signal:data_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface FIXED_IO_ps_porb xilinx.com:signal:data_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface FIXED_IO_ps_srstb xilinx.com:signal:data_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface MIO xilinx.com:signal:data_rtl:1.0 [ipx::current_core]
set_property core_revision 2 [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums [ipx::current_core]
ipx::save_core [ipx::current_core]
set_property  ip_repo_paths  /home/jamey/connectal/tests/nvme_strstr [current_project]
update_ip_catalog
ipx::check_integrity -quiet [ipx::current_core]
ipx::archive_core /home/jamey/connectal/tests/nvme_strstr/accelerated.tech_user_nvme_strstr_1.0.zip [ipx::current_core]
set_property core_revision 3 [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums [ipx::current_core]
ipx::save_core [ipx::current_core]
update_ip_catalog -rebuild -repo_path /home/jamey/connectal/tests/nvme_strstr
ipx::check_integrity -quiet [ipx::current_core]
ipx::archive_core /home/jamey/connectal/tests/nvme_strstr/accelerated.tech_user_nvme_strstr_1.0.zip [ipx::current_core]
launch_runs synth_1 -jobs 12
wait_on_run synth_1
ipx::remove_bus_interface FIXED_IO_ddr_vrn [ipx::current_core]
ipx::remove_bus_interface FIXED_IO_ddr_vrp [ipx::current_core]
ipx::remove_bus_interface FIXED_IO_ps_porb [ipx::current_core]
ipx::remove_bus_interface FIXED_IO_ps_srstb [ipx::current_core]
ipx::remove_bus_interface MIO [ipx::current_core]
ipx::remove_bus_interface FIXED_IO_ps_clk [ipx::current_core]
ipx::create_abstraction_definition xilinx zynq7 FIXED_IO_rtl 1.0
ipx::create_bus_definition xilinx zynq7 FIXED_IO 1.0
set_property xml_file_name /home/jamey/connectal/tests/nvme_strstr/ip_repo/FIXED_IO_rtl.xml [ipx::current_busabs]
set_property xml_file_name /home/jamey/connectal/tests/nvme_strstr/ip_repo/FIXED_IO.xml [ipx::current_busdef]
set_property bus_type_vlnv xilinx:zynq7:FIXED_IO:1.0 [ipx::current_busabs]
ipx::save_abstraction_definition [ipx::current_busabs]
ipx::save_bus_definition [ipx::current_busdef]
ipx::add_bus_abstraction_port FIXED_IO_ddr_vrn [ipx::current_busabs]
ipx::add_bus_abstraction_port FIXED_IO_ddr_vrp [ipx::current_busabs]
ipx::add_bus_abstraction_port MIO [ipx::current_busabs]
ipx::add_bus_abstraction_port FIXED_IO_ps_clk [ipx::current_busabs]
ipx::add_bus_abstraction_port FIXED_IO_ps_porb [ipx::current_busabs]
ipx::add_bus_abstraction_port FIXED_IO_ps_srstb [ipx::current_busabs]
ipx::save_bus_definition [ipx::current_busdef]
ipx::save_abstraction_definition [ipx::current_busabs]
update_ip_catalog -rebuild
update_ip_catalog -rebuild -repo_path /home/jamey/connectal/tests/nvme_strstr
ipx::infer_bus_interface {FIXED_IO_ddr_vrn FIXED_IO_ddr_vrp MIO FIXED_IO_ps_clk FIXED_IO_ps_porb FIXED_IO_ps_srstb} xilinx:zynq7:FIXED_IO:1.0 [ipx::current_core]
set_property name FIXED_IO [ipx::get_bus_interfaces FIXED_IO_1 -of_objects [ipx::current_core]]
ipx::remove_bus_interface FIXED_IO_ddr_vrn [ipx::current_core]
ipx::remove_bus_interface FIXED_IO_ps_clk [ipx::current_core]
ipx::create_abstraction_definition accelerated.tech zynq7 FIXED_IO_rtl 1.0
ipx::create_bus_definition accelerated.tech zynq7 FIXED_IO 1.0
set_property xml_file_name /home/jamey/connectal/tests/nvme_strstr/ip_repo/FIXED_IO_rtl.xml [ipx::current_busabs]
set_property xml_file_name /home/jamey/connectal/tests/nvme_strstr/ip_repo/FIXED_IO.xml [ipx::current_busdef]
set_property bus_type_vlnv accelerated.tech:zynq7:FIXED_IO:1.0 [ipx::current_busabs]
ipx::save_abstraction_definition [ipx::current_busabs]
ipx::save_bus_definition [ipx::current_busdef]
set_property  ip_repo_paths  /home/jamey/connectal/tests/nvme_strstr/ip_repo [current_project]
ipx::add_bus_abstraction_port FIXED_IO_ddr_vrn [ipx::current_busabs]
ipx::add_bus_abstraction_port FIXED_IO_ddr_vrp [ipx::current_busabs]
ipx::add_bus_abstraction_port MIO [ipx::current_busabs]
ipx::add_bus_abstraction_port FIXED_IO_ps_clk [ipx::current_busabs]
ipx::add_bus_abstraction_port FIXED_IO_ps_porb [ipx::current_busabs]
ipx::add_bus_abstraction_port FIXED_IO_ps_srstb [ipx::current_busabs]
ipx::save_bus_definition [ipx::current_busdef]
ipx::save_abstraction_definition [ipx::current_busabs]
update_ip_catalog -rebuild
update_ip_catalog
ipx::infer_bus_interface {FIXED_IO_ddr_vrn FIXED_IO_ddr_vrp MIO FIXED_IO_ps_clk FIXED_IO_ps_porb FIXED_IO_ps_srstb} accelerated.tech:zynq7:FIXED_IO:1.0 [ipx::current_core]
set_property name FIXED_IO [ipx::get_bus_interfaces FIXED_IO_1 -of_objects [ipx::current_core]]
set_property core_revision 2 [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums [ipx::current_core]
ipx::save_core [ipx::current_core]
set_property  ip_repo_paths  {/home/jamey/connectal/tests/nvme_strstr /home/jamey/connectal/tests/nvme_strstr/ip_repo} [current_project]
update_ip_catalog
ipx::check_integrity -quiet [ipx::current_core]
ipx::archive_core /home/jamey/connectal/tests/nvme_strstr/accelerated.tech_user_nvme100_1.0.zip [ipx::current_core]
update_compile_order -fileset sources_1
ipx::infer_bus_interface FIXED_IO_ddr_vrp xilinx.com:signal:data_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface FIXED_IO_ps_porb xilinx.com:signal:data_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface FIXED_IO_ps_srstb xilinx.com:signal:data_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface MIO xilinx.com:signal:video_frame_sync_rtl:1.0 [ipx::current_core]
ipx::add_bus_interface accel_request [ipx::current_core]
set_property abstraction_type_vlnv xilinx.com:interface:axis_rtl:1.0 [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]
set_property bus_type_vlnv xilinx.com:interface:axis:1.0 [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]
ipx::add_port_map TDATA [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]
set_property physical_name accel_request_tdata_v [ipx::get_port_maps TDATA -of_objects [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]]
ipx::add_port_map TLAST [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]
set_property physical_name accel_request_tlast_v [ipx::get_port_maps TLAST -of_objects [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]]
ipx::add_port_map TVALID [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]
set_property physical_name accel_request_tvalid_v [ipx::get_port_maps TVALID -of_objects [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]]
ipx::add_port_map TKEEP [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]
set_property physical_name accel_request_tkeep_v [ipx::get_port_maps TKEEP -of_objects [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]]
ipx::add_port_map TREADY [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]
set_property physical_name accel_request_tready [ipx::get_port_maps TREADY -of_objects [ipx::get_bus_interfaces accel_request -of_objects [ipx::current_core]]]
ipx::infer_bus_interface {accel_msgIn_tdata_v accel_msgIn_tkeep_v accel_msgIn_tlast_v accel_msgIn_tready accel_msgIn_tvalid_v} xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {accel_dataIn_tdata_v accel_dataIn_tkeep_v accel_dataIn_tlast_v accel_dataIn_tready accel_dataIn_tvalid_v} xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
set_property name MIO [ipx::get_bus_interfaces video_frame_sync_1 -of_objects [ipx::current_core]]
ipx::add_port_map TREADY [ipx::get_bus_interfaces accel_msgOut -of_objects [ipx::current_core]]
set_property physical_name accel_msgOut_tready_v [ipx::get_port_maps TREADY -of_objects [ipx::get_bus_interfaces accel_msgOut -of_objects [ipx::current_core]]]
ipx::add_port_map TREADY [ipx::get_bus_interfaces accel_dataOut -of_objects [ipx::current_core]]
set_property physical_name accel_dataOut_tready_v [ipx::get_port_maps TREADY -of_objects [ipx::get_bus_interfaces accel_dataOut -of_objects [ipx::current_core]]]
ipx::add_port_map TREADY [ipx::get_bus_interfaces accel_response -of_objects [ipx::current_core]]
set_property physical_name accel_response_tready_v [ipx::get_port_maps TREADY -of_objects [ipx::get_bus_interfaces accel_response -of_objects [ipx::current_core]]]
set_property core_revision 3 [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums [ipx::current_core]
ipx::save_core [ipx::current_core]
set_property  ip_repo_paths  /home/jamey/connectal.bisect/tests/nvme_strstr/miniitx100 [current_project]
update_ip_catalog
