
CONNECTALDIR?=../..
S2H_INTERFACES = MemrwRequest:Memrw.request
H2S_INTERFACES = Memrw:MemrwIndication
MEM_INTERFACES = lMemrw.dmaReadClient,lMemrw.dmaWriteClient
BSVFILES = Memrw.bsv
CPPFILES=testmemrw.cpp

include $(CONNECTALDIR)/Makefile.connectal
