
CONNECTALDIR?=../..
S2H_INTERFACES = TestRequest:Test.request
H2S_INTERFACES = Test:TestIndication
BSVFILES = Test.bsv
CPPFILES=test.cpp

NUMBER_OF_MASTERS =0

include $(CONNECTALDIR)/Makefile.connectal

