
BSVDIR=../../bsv
S2H = MempokeRequest DmaConfig
H2S = MempokeIndication DmaIndication
BSVFILES = Mempoke.bsv Top.bsv
CPPFILES=testmempoke.cpp
Dma = Dma
PINS = Std
#XBSVFLAGS=-DTRACE_AXI

include ../../Makefile.common
