
BSVDIR=../../bsv
S2H = MempokeRequest DmaRequest
H2S = MempokeIndication DmaIndication
BSVFILES = Mempoke.bsv $(BSVDIR)/PortalMemory.bsv
CPPFILES=testmempoke.cpp
Dma = Dma
PINS = Std

include ../../Makefile.common
