
BSVDIR=../../bsv
S2H = MempokeRequest DmaConfig
H2S = MempokeIndication DmaIndication
BSVFILES = Mempoke.bsv Top.bsv
CPPFILES=testmempoke.cpp
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
