
CONNECTALDIR?=../..
INTERFACES = SerialconfigRequest SerialconfigIndication
## all the BSV files to be scanned for types and interfaces
BSVFILES = Serialconfig.bsv Top.bsv
## the source files in the example
CPPFILES=testserialconfig.cpp
NUMBER_OF_MASTERS =0

include $(CONNECTALDIR)/Makefile.connectal

