
S2H = MemrwRequest DmaConfig
H2S = MemrwIndication DmaIndication
BSVFILES = Memrw.bsv Top.bsv
CPPFILES=testmemrw.cpp
Dma = Dma
PINS = Std
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
