
MEMCPYDIR=../../examples/memcpy
S2H = MemcpyRequest
H2S = MemcpyIndication
BSVFILES = $(MEMCPYDIR)/Memcpy.bsv Top.bsv
CPPFILES=testmemcpy.cpp
#CONNECTALFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.connectal
