
MEMCPYDIR=../../examples/memcpy
INTERFACES = MemcpyRequest MemcpyIndication
BSVFILES = $(MEMCPYDIR)/Memcpy.bsv Top.bsv
CPPFILES=testmemcpy.cpp
#CONNECTALFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.connectal
