obj-m = portalalloc.o

KVERSION = $(shell uname -r)
UTILDIR = ../../cpp/
BASEDIR = ../../

default:
	make -C /lib/modules/$(KVERSION)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(KVERSION)/build M=$(PWD) clean
	rm -f a.out