
CONNECTALDIR?=../..
S2H_INTERFACES = DmaRequest:DmaLoopback.request0,request1
H2S_INTERFACES = DmaLoopback:DmaIndication,DmaIndication
MEM_READ_INTERFACES = lDmaLoopback.readClient
MEM_WRITE_INTERFACES = lDmaLoopback.writeClient
BSVFILES = DmaController.bsv
CPPFILES=testdmacopy.cpp

include $(CONNECTALDIR)/Makefile.connectal
