
CONNECTALDIR?=../..
S2H_INTERFACES = DmaRequest:DmaCopy.request
H2S_INTERFACES = DmaCopy:DmaIndication
MEM_READ_INTERFACES = lDmaCopy.readClient
MEM_WRITE_INTERFACES = lDmaCopy.writeClient
BSVFILES = Dma.bsv
CPPFILES=testdmacopy.cpp

include $(CONNECTALDIR)/Makefile.connectal
