CONNECTALDIR?=../..
S2H_INTERFACES = TestRequest:Test.request
H2S_INTERFACES = Test:TestIndication
MEM_READ_INTERFACES = lTest.dmaClient

BSVFILES = Test.bsv
CPPFILES=test.cpp

include $(CONNECTALDIR)/Makefile.connectal
