
CONNECTALDIR?=../..
S2H_INTERFACES = TestRequest:Test.request
H2S_INTERFACES = Test:TestIndication
MEM_INTERFACES = mkMemServerR:lTest.dmaClient
BSVFILES = Test.bsv
CPPFILES=test.cpp

include $(CONNECTALDIR)/Makefile.connectal
