
CONNECTALDIR?=../..
S2H_INTERFACES = TestRequest:Test.request
H2S_INTERFACES = TestIndication:Test
MEM_INTERFACES = MemServer.request:/lTest.dmaClient,cons\(lMMU,nil\):PhysAddrWidth,DataBusWidth,\`NumberOfMasters:mkMemServerR
BSVFILES = Test.bsv
CPPFILES=test.cpp

include $(CONNECTALDIR)/Makefile.connectal
