S2H = PortalPerfRequest
H2S = PortalPerfIndication
BSVFILES = Repeat.bsv PortalPerf.bsv Top.bsv
CPPFILES=testportalperf.cpp
XBSVFLAGS += --bscflags " -D NumberOfMasters=0"

include ../../Makefile.common

