
CONNECTALDIR?=../..
INTERFACES = PortalPerfRequest PortalPerfIndication
BSVFILES = Repeat.bsv PortalPerf.bsv Top.bsv
CPPFILES=testportalperf.cpp
NUMBER_OF_MASTERS =0

include $(CONNECTALDIR)/Makefile.connectal

