
S2H = MaxcommonsubseqRequest
H2S = MaxcommonsubseqIndication
BSVFILES = Maxcommonsubseq.bsv Top.bsv ../../lib/deprecated/DmaUtils.bsv
CPPFILES=testmaxcommonsubseq.cpp
#CONNECTALFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.connectal
