
CONNECTALDIR?=../..
INTERFACES = MaxcommonsubseqRequest MaxcommonsubseqIndication
BSVFILES = Maxcommonsubseq.bsv Top.bsv $(CONNECTALDIR)/lib/deprecated/DmaUtils.bsv
CPPFILES=testmaxcommonsubseq.cpp
#CONNECTALFLAGS=--bscflags " -D TRACE_AXI"

include $(CONNECTALDIR)/Makefile.connectal
