
BSVDIR=../../bsv
S2H = MaxcommonsubseqRequest DmaConfig
H2S = MaxcommonsubseqIndication DmaIndication
BSVFILES = Maxcommonsubseq.bsv Top.bsv
CPPFILES=testmaxcommonsubseq.cpp
Dma = Dma
PINS = Std

include ../../Makefile.common
