
CONNECTALDIR?=../..
INTERFACES = Simple MMURequest MMUIndication MemServerRequest MemServerIndication SharedMemoryPortalConfig
BSVFILES = SimpleIF.bsv Top.bsv
CPPFILES=testsimple.cpp $(CONNECTALDIR)/cpp/portalShared.c

include $(CONNECTALDIR)/Makefile.connectal
