

S2H = PipeMulRequest
H2S = PipeMulIndication
BSVFILES = PipeMulTB.bsv  Top.bsv
CPPFILES=testpipe_mul.cpp
## uncomment the following line to enable AXI trace
# XBSVFLAGS="--bscflags=-D TRACE_AXI"
NUMBER_OF_MASTERS =0

include ../../Makefile.common

