CONNECTALDIR?=../..
INTERFACES = SignalGenRequest SignalGenIndication \
	BlueScopeEventPIORequest BlueScopeEventPIOIndication

BSVFILES = ../../lib/bsv/BlueScopeEventPIO.bsv SignalGen.bsv Top.bsv
CPPFILES=testbluescopeeventpio.cpp

include $(CONNECTALDIR)/Makefile.connectal
