
CONNECTALDIR?=../..
INTERFACES = RingRequest RingIndication
BSVFILES = Ring.bsv RingTypes.bsv Top.bsv $(CONNECTALDIR)/lib/deprecated/DmaUtils.bsv
CPPFILES=testring.cpp

include $(CONNECTALDIR)/Makefile.connectal

