
S2H = NandSimRequest StrstrRequest
H2S = NandSimIndication StrstrIndication
BSVFILES = ../nandsim/NandSim.bsv ../strstr/Strstr.bsv Top.bsv
CPPFILES=test.cpp
XBSVFLAGS = -D NANDSIMHACK

include ../../Makefile.xbsv
