
INTERFACES = SimpleRequest SimpleIndication
BSVFILES = Simple.bsv Top.bsv
#original user program CPPFILES=testsimple.cpp
CPPFILES=simple_manual.c
NUMBER_OF_MASTERS =0
#CONNECTALFLAGS += --bscflags " -D TRACE_AXI"
CONNECTALFLAGS += -D NO_CPP_PORTAL_CODE

include ../../Makefile.connectal
