
BSVDIR=../../bsv
S2H = SimpleRequest
H2S = SimpleIndication
BSVFILES = Simple.bsv Top.bsv
#original user program CPPFILES=testsimple.cpp
CPPFILES=manualsimple.cpp
XBSVFLAGS += --bscflags " -D NumberOfMasters=0"
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
