
BSVDIR=../../bsv
S2H = SimpleRequest
H2S = SimpleIndication
BSVFILES = Simple.bsv Top.bsv
#original user program CPPFILES=testsimple.cpp
CPPFILES=simple_manual.c
NUMBER_OF_MASTERS =0
#XBSVFLAGS += --bscflags " -D TRACE_AXI"
XBSVFLAGS += -D NO_CPP_PORTAL_CODE

include ../../Makefile.common
