obj-m += pcieportal.o
obj-m += portalmem.o
EXTRA_CFLAGS = -DDRIVER_VERSION="KBUILD_STR(@VERSION@)"

pcieportal.c: driverversion.h

driverversion.h:
	echo '#define DRIVER_VERSION "@VERSION@"' > driverversion.h
