
BSVDIR=../../bsv
S2H = MemreadRequest DmaConfig
H2S = MemreadIndication DmaIndication
BSVFILES = Memread.bsv Top.bsv
CPPFILES=testmemread.cpp
XBSVFLAGS += --bscflags " -D DataBusWidth=128"

include ../../Makefile.common

