
BSVDIR=../../bsv
S2H = MemreadRequest
H2S = MemreadIndication
BSVFILES = Memread.bsv Top.bsv
#CPPFILES=testmemread.cpp
#CPPFILES=memread_manual.cpp
CPPFILES=memread_manual_manager.c
#XBSVFLAGS += --bscflags " -D TRACE_AXI"
XBSVFLAGS += -D NO_CPP_PORTAL_CODE

include ../../Makefile.common

