
BSVDIR=../../bsv
LIBBSVDIR=../../lib/bsv
S2H = YuvRequest
H2S = YuvIndication
BSVFILES =  YuvRequest.bsv Top.bsv
CPPFILES= testyuv.cpp

NUMBER_OF_MASTERS =0
#XBSVFLAGS+=  -D TRACE_AXI

include ../../Makefile.xbsv
