
BSVDIR=../../bsv
LIBBSVDIR=../../lib/bsv
S2H = YuvRequest
H2S = YuvIndication
BSVFILES =  YuvRequest.bsv Top.bsv
CPPFILES= testyuv.cpp

XBSVFLAGS += -D NumberOfMasters=0
#XBSVFLAGS+=  -D TRACE_AXI

include ../../Makefile.common
