
CONNECTALDIR?=../..
INTERFACES = FibRequest FibIndication
## all the BSV files to be scanned for types and interfaces
BSVFILES = FibWide.bsv Top.bsv
## the source files in the example
CPPFILES=testfib.cpp
## uncomment the following line to enable AXI trace
# CONNECTALFLAGS="--bscflags=-D TRACE_AXI"
NUMBER_OF_MASTERS =0

include $(CONNECTALDIR)/Makefile.connectal

