
## hardware interfaces invoked from software (requests)
S2H = FibRequest
## software interfaces invoked from hardware (indications)
H2S = FibIndication
## all the BSV files to be scanned for types and interfaces
BSVFILES = Fib.bsv Top.bsv
## the source files in the example
CPPFILES=testfib.cpp
## uncomment the following line to enable AXI trace
# XBSVFLAGS="--bscflags=-D TRACE_AXI"

include ../../Makefile.common

