# Test program for multiple interfaces of same datatype
CONNECTALDIR?=../..
S2H_INTERFACES = EchoRequest:Echo.request1,Echo.request2
H2S_INTERFACES = Echo:EchoIndication,EchoIndication

BSVFILES = Echo.bsv
CPPFILES= testecho.cpp

include $(CONNECTALDIR)/Makefile.connectal

