
BSVDIR=../../bsv
S2H = PcieTestBenchRequest
H2S = PcieTestBenchIndication
BSVFILES = PcieTestBench.bsv Top.bsv
CPPFILES=testpcie.cpp
NUMBER_OF_MASTERS =0
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
