
CONNECTALDIR?=../..
INTERFACES = ReadTestRequest ReadTestIndication
BSVFILES = ReadTest.bsv $(CONNECTALDIR)/bsv/PlatformTypes.bsv ReadTestEnum.bsv
CPPFILES=testmemread.cpp
NUMBER_OF_USER_TILES = 2

include $(CONNECTALDIR)/Makefile.connectal
