
CONNECTALDIR?=../..
INTERFACES = MemreadRequest MemreadIndication
BSVFILES = Memread.bsv $(CONNECTALDIR)/bsv/PlatformTypes.bsv
CPPFILES=testmemread.cpp
NUMBER_OF_MASTERS = 1

include $(CONNECTALDIR)/Makefile.connectal
