
INTERFACES = NocRequest NocIndication
## all the BSV files to be scanned for types and interfaces
BSVFILES = Noc2d.bsv Top.bsv
## the source files in the example
CPPFILES=testnoc2d.cpp
## uncomment the following line to enable AXI trace
# CONNECTALFLAGS="--bscflags=-D TRACE_AXI"
NUMBER_OF_MASTERS =0

include ../../Makefile.connectal

