
CONNECTALDIR?=../..
S2H_INTERFACES = LedControllerRequest:LedController.request
BSVFILES = LedController.bsv
CPPFILES= testleds.cpp
NUMBER_OF_MASTERS =0
PIN_TYPE = LEDS

AUTOTOP = --interface pins:LedController.leds --importfiles Leds

include $(CONNECTALDIR)/Makefile.connectal
