CONNECTALDIR?=../..
S2H_INTERFACES = SerialconfigIndication
H2S_INTERFACES = SerialconfigRequest

BSVFILES = Serialconfig.bsv
CPPFILES=testserialconfig.cpp

include $(CONNECTALDIR)/Makefile.connectal
