CONNECTALDIR?=../..
S2H_INTERFACES = SerialconfigRequest:Serialconfig.request
H2S_INTERFACES = Serialconfig:SerialconfigIndication

BSVFILES = Serialconfig.bsv
CPPFILES=testserialconfig.cpp

include $(CONNECTALDIR)/Makefile.connectal
