
BSVDIR=../../bsv
S2H = RingRequest DMARequest
H2S = RingIndication DMAIndication
BSVFILES = Ring.bsv Top.bsv RingTypes.bsv $(BSVDIR)/PortalMemory.bsv
CPPFILES=testring.cpp
DMA = Dma
PINS = Std

include ../../Makefile.common

