
BSVDIR=../../bsv
S2H = RingRequest DmaConfig
H2S = RingIndication DmaIndication
BSVFILES = Ring.bsv RingTypes.bsv Top.bsv
CPPFILES=testring.cpp
Dma = Dma
PINS = Std
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common

