obj-m = portalmem.o

KVERSION=$(shell uname -r)
export KROOT=/lib/modules/$(KVERSION)/build

default:
	$(MAKE) -C $(KROOT) M=$(PWD) modules
	#rmmod portalmem || true
	#insmod ./portalmem.ko
	#chmod 777 /dev/portalmem

clean:
	$(MAKE) -C $(KROOT) M=$(PWD) clean
	rm -f a.out

