obj-m = portalmem.o

export KROOT=/lib/modules/$(shell uname -r)/build

default:
	$(MAKE) -C $(KROOT) M=$(PWD) modules
	sudo rmmod portalmem || true
	sudo insmod ./portalmem.ko
	sudo chmod 777 /dev/portalmem

clean:
	$(MAKE) -C $(KROOT) M=$(PWD) clean
	rm -f a.out

