obj-m = portalmem.o

KVERSION = $(shell uname -r)
UTILDIR = ../../cpp/
BASEDIR = ../../

default:
	make -C /lib/modules/$(KVERSION)/build M=$(PWD) modules
	sudo rmmod portalmem || true
	sudo insmod ./portalmem.ko
	sudo chmod 777 /dev/portalmem

clean:
	make -C /lib/modules/$(KVERSION)/build M=$(PWD) clean
	rm -f a.out

