CONNECTALDIR?=../../
S2H_INTERFACES = VaddRequest:Vadd.request
H2S_INTERFACES = Vadd:VaddResponse

BSVFILES = bsv/Vadd.bsv
CPPFILES = testvadd.cpp

CONNECTALFLAGS += -V solution1/impl/verilog

include $(CONNECTALDIR)/Makefile.connectal
