CONNECTALDIR?=../..
S2H_INTERFACES = MemlatencyRequest:Memlatency.request
H2S_INTERFACES = Memlatency:MemlatencyIndication
MEM_READ_INTERFACES = lMemlatency.dmaReadClient
MEM_WRITE_INTERFACES = lMemlatency.dmaWriteClient

BSVFILES = Memlatency.bsv
CPPFILES = testmemlatency.cpp

include $(CONNECTALDIR)/Makefile.connectal
