
S2H = MemlatencyRequest DmaConfig
H2S = MemlatencyIndication DmaIndication
BSVFILES = Memlatency.bsv Top.bsv
CPPFILES=testmemlatency.cpp
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
