
CONNECTALDIR?=../..
INTERFACES = SignalGenRequest SignalGenIndication \
	BlueScopeEventRequest BlueScopeEventIndication
BSVFILES = ../../lib/bsv/BlueScopeEvent.bsv SignalGen.bsv Top.bsv
CPPFILES=testbluescopeevent.cpp

include $(CONNECTALDIR)/Makefile.connectal
