
BSVDIR=../../bsv
S2H = SpliceRequest
H2S = SpliceIndication
BSVFILES = Splice.bsv Top.bsv ../../lib/deprecated/DmaUtils.bsv
CPPFILES=testsplice.cpp
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.xbsv
