
BSVDIR=../../bsv
S2H = SpliceRequest DmaConfig
H2S = SpliceIndication DmaIndication
BSVFILES = Splice.bsv Top.bsv ../../lib/deprecated/DmaUtils.bsv
CPPFILES=testsplice.cpp
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
