
BSVDIR=../../bsv
S2H = SpliceRequest DmaConfig
H2S = SpliceIndication DmaIndication
BSVFILES = Splice.bsv Top.bsv
CPPFILES=testsplice.cpp
Dma = Dma
PINS = Std
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
