
S2H = BscanRequest
H2S = BscanIndication
BSVFILES = BscanRequest.bsv Top.bsv
CPPFILES=testbscan.cpp
NUMBER_OF_MASTERS =0
XBSVFLAGS += --bscflags " -D USES_BSCAN"
# XBSVFLAGS += --bscflags " -D TRACE_AXI"

include ../../Makefile.xbsv

