
S2H = BscanRequest
H2S = BscanIndication
BSVFILES = BscanRequest.bsv Top.bsv
CPPFILES=testbscan.cpp
XBSVFLAGS += --bscflags " -D NumberOfMasters=0"
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common

