
S2H = MemcpyRequest BlueScopeRequest
H2S = MemcpyIndication BlueScopeIndication
BSVFILES = Memcpy.bsv ../../lib/bsv/BlueScope.bsv Top.bsv
CPPFILES=testbluescope.cpp
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
