
BSVDIR=../../bsv
S2H = MemcpyRequest BlueScopeRequest DmaConfig
H2S = MemcpyIndication BlueScopeIndication DmaIndication
BSVFILES = Memcpy.bsv $(BSVDIR)/BlueScope.bsv Top.bsv
CPPFILES=testbluescope.cpp
Dma = Dma
PINS = Std
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
