
CONNECTALDIR?=../..
S2H_INTERFACES = Memread2Request:Memread2.request
H2S_INTERFACES = Memread2:Memread2Indication
MEM_INTERFACES = lMemread2.dmaClients,nil
BSVFILES = Memread2.bsv
CPPFILES=testmemread2.cpp

include $(CONNECTALDIR)/Makefile.connectal
