
CONNECTALDIR?=../..
INTERFACES = Memread2Request Memread2Indication
BSVFILES = Memread2.bsv Top.bsv $(CONNECTALDIR)/lib/deprecated/DmaUtils.bsv
CPPFILES=testmemread2.cpp
#CONNECTALFLAGS=--bscflags " -D TRACE_AXI"

include $(CONNECTALDIR)/Makefile.connectal
