
CONNECTALDIR?=../..
INTERFACES = EchoRequest EchoIndication EchoRequestSW EchoIndicationSW
## all the BSV files to be scanned for types and interfaces
BSVFILES = Echo.bsv Top.bsv
## the source files in the example
CPPFILES=daemon.cpp
CPPFILES2=testecho.cpp

NUMBER_OF_MASTERS =0

include $(CONNECTALDIR)/Makefile.connectal
