
S2H = RegexpRequest
H2S = RegexpIndication
BSVFILES = Regexp.bsv Top.bsv
CPPFILES=testregexp.cpp regex-matcher.cpp
CONNECTALFLAGS = -D DEGPAR=4 -D MAX_NUM_STATES=32 -D MAX_NUM_CHARS=32 
RUN_ARGS = test.bin


include ../../Makefile.connectal
