
CONNECTALDIR?=../..
INTERFACES = SpliceRequest SpliceIndication
BSVFILES = Splice.bsv Top.bsv $(CONNECTALDIR)/lib/deprecated/DmaUtils.bsv
CPPFILES=testsplice.cpp

include $(CONNECTALDIR)/Makefile.connectal
