
####################################################################################
# Generated by Vivado 2014.4 built on 'Tue Nov 18 16:48:31 MST 2014' by 'xbuild'
# Command Used: write_xdc -cell [get_cells top_lInnerProd_ip] -file innerprod.xdc
####################################################################################


# User Generated physical constraints 

create_macro innerprod_0
update_macro [get_macros innerprod_0] -rlocs {macroTile_0/tile_3/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y3 macroTile_0/tile_3/dsp/dsp DSP48_X0Y3 macroTile_0/tile_0/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y0 macroTile_0/tile_0/dsp/dsp DSP48_X0Y0 macroTile_0/tile_1/dsp/dsp DSP48_X0Y1 macroTile_0/tile_2/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y2 macroTile_0/tile_1/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y1 macroTile_0/tile_2/dsp/dsp DSP48_X0Y2}
create_macro innerprod_1
update_macro [get_macros innerprod_1] -rlocs {macroTile_1/tile_3/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y3 macroTile_1/tile_3/dsp/dsp DSP48_X0Y3 macroTile_1/tile_0/dsp/dsp DSP48_X0Y0 macroTile_1/tile_0/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y0 macroTile_1/tile_1/dsp/dsp DSP48_X0Y1 macroTile_1/tile_1/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y1 macroTile_1/tile_2/dsp/dsp DSP48_X0Y2 macroTile_1/tile_2/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y2}
create_macro innerprod_2
update_macro [get_macros innerprod_2] -rlocs {macroTile_2/tile_3/dsp/dsp DSP48_X0Y3 macroTile_2/tile_0/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y0 macroTile_2/tile_3/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y3 macroTile_2/tile_1/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y1 macroTile_2/tile_0/dsp/dsp DSP48_X0Y0 macroTile_2/tile_1/dsp/dsp DSP48_X0Y1 macroTile_2/tile_2/dsp/dsp DSP48_X0Y2 macroTile_2/tile_2/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y2}
create_macro innerprod_3
update_macro [get_macros innerprod_3] -rlocs {macroTile_3/tile_3/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y3 macroTile_3/tile_3/dsp/dsp DSP48_X0Y3 macroTile_3/tile_0/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y0 macroTile_3/tile_0/dsp/dsp DSP48_X0Y0 macroTile_3/tile_2/dsp/dsp DSP48_X0Y2 macroTile_3/tile_2/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y2 macroTile_3/tile_1/dsp/dsp DSP48_X0Y1 macroTile_3/tile_1/reqFifo_fifos_0/genblk5_0.fifo_18_bl_1.fifo_18_bl_1 RAMB18_X0Y1}
