
CONNECTALDIR?=../..
INTERFACES = MemwriteRequest MemwriteIndication
BSVFILES = Memwrite.bsv Top.bsv
CPPFILES = testmemwrite.cpp

CONNECTALFLAGS += -D USE_ACP

include $(CONNECTALDIR)/Makefile.connectal

