CONNECTALDIR?=../..
INTERFACES = MemwriteRequest MemwriteIndication

BSVFILES = Memwrite.bsv $(CONNECTALDIR)/bsv/PlatformTypes.bsv MemwriteEnum.bsv
CPPFILES=testmemwrite.cpp
NUMBER_OF_USER_TILES = 2

include $(CONNECTALDIR)/Makefile.connectal
