CONNECTALDIR?=../..
S2H_INTERFACES = ReadTestRequest:ReadTest.request
H2S_INTERFACES = ReadTest:ReadTestIndication
MEM_READ_INTERFACES = lReadTest.dmaClient

BSVFILES = ReadTest.bsv
CPPFILES=testmemread.cpp

include $(CONNECTALDIR)/Makefile.connectal
