
CONNECTALDIR?=../..
S2H_INTERFACES = MemreadRequest:Memread.request
H2S_INTERFACES = Memread:MemreadIndication
MEM_INTERFACES = mkMemServerR:lMemread.dmaClient
BSVFILES = Memread.bsv
CPPFILES=testmemread.cpp

include $(CONNECTALDIR)/Makefile.connectal
