CONNECTALDIR?=../..
S2H_INTERFACES = MifoTestRequest:MifoTest.request
H2S_INTERFACES = MifoTest:MifoTestIndication

BSVFILES = MifoTest.bsv
CPPFILES=testmifo.cpp

include $(CONNECTALDIR)/Makefile.connectal
