
BSVDIR=../../bsv
S2H = MifoTestRequest
H2S = MifoTestIndication
BSVFILES = MifoTest.bsv Top.bsv
CPPFILES=testmifo.cpp
NUMBER_OF_MASTERS =0
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
