
INTERFACES = Swallow EchoRequest EchoIndication DisplayInd
## all the BSV files to be scanned for types and interfaces
BSVFILES = Echo.bsv Swallow.bsv Top.bsv
## the source files in the example
CPPFILES=testecho.cpp
## uncomment the following line to enable AXI trace
# CONNECTALFLAGS="--bscflags=-D TRACE_AXI"
NUMBER_OF_MASTERS =0

USE_PRINTF = 1

include ../../Makefile.connectal

