CONNECTALDIR?=../..
INTERFACES = Swallow EchoRequest EchoIndication DisplayInd

BSVFILES = Echo.bsv SwallowIF.bsv Top.bsv
CPPFILES=testecho.cpp
USE_PRINTF = 1

include $(CONNECTALDIR)/Makefile.connectal
