
CONNECTALDIR?=../..
BSVFILES = ../simple/Simple.bsv LinkIF.bsv
CPPFILES=testsimple.cpp
NUMBER_OF_MASTERS =0
S2H_INTERFACES = LinkRequest:Link.linkRequest SimpleRequest:Link.simpleRequest
H2S_INTERFACES = Link:SimpleRequest

include $(CONNECTALDIR)/Makefile.connectal
