
CONNECTALDIR?=../..
BSVFILES = ../simple/Simple.bsv LinkIF.bsv
CPPFILES=testsimple.cpp
NUMBER_OF_MASTERS =0
S2H_INTERFACES = SimpleRequest:Link.simpleRequest LinkRequest:Link.linkRequest
H2S_INTERFACES = Link:SimpleRequest

include $(CONNECTALDIR)/Makefile.connectal
