CONNECTALDIR?=../..
S2H_INTERFACES = LinkRequest:Link.linkRequest SimpleRequest:Link.simpleRequest
H2S_INTERFACES = Link:SimpleRequest

BSVFILES = ../simple/Simple.bsv LinkIF.bsv
CPPFILES=testsimple.cpp

include $(CONNECTALDIR)/Makefile.connectal
