
BSVDIR=../../bsv
S2H = SimpleRequest
H2S = SimpleIndication
BSVFILES = Simple.bsv Top.bsv
CPPFILES=testsimple.cpp
Dma = 
PINS = Std
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
