
S2H = PerfRequest
H2S = PerfIndication
BSVFILES = Perf.bsv Top.bsv ../../lib/deprecated/DmaUtils.bsv
CPPFILES=testperf.cpp
#CONNECTALFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.connectal
