
BSVDIR=../../bsv
S2H = PerfRequest DmaConfig
H2S = PerfIndication DmaIndication
BSVFILES = Perf.bsv $(BSVDIR)/PortalMemory.bsv Top.bsv
CPPFILES=testperf.cpp
Dma = Dma
PINS = Std

include ../../Makefile.common
