
CONNECTALDIR?=../..
S2H_INTERFACES = EchoRequest:Echo.request SwallowRequest:Swallow.request
H2S_INTERFACES = Echo:EchoIndication
BSVFILES = Echo.bsv Swallow.bsv
CPPFILES=daemon.cpp
NUMBER_OF_MASTERS =0

include $(CONNECTALDIR)/Makefile.connectal
