
S2H = NandSimRequest StrstrRequest
H2S = NandSimIndication StrstrIndication
BSVFILES = ../../lib/bsv/NandSim.bsv ../../lib/bsv/Strstr.bsv ../../examples/algo1_nandsim/Top.bsv ../../lib/bsv/NandSimNames.bsv
CPPFILES=../../examples/algo1_nandsim/test.cpp
CPPFILES2=../../examples/nandsim/testnandsim.cpp
XBSVFLAGS += -D ALGO1_NANDSIM

include ../../Makefile.xbsv
