## algo1_nandsim_manual


S2H = NandSimRequest StrstrRequest
H2S = NandSimIndication StrstrIndication
BSVFILES = ../../lib/bsv/NandSim.bsv ../../lib/bsv/Strstr.bsv ../../examples/algo1_nandsim/Top.bsv ../../lib/bsv/NandSimNames.bsv
CPPFILES=algo1.cpp
CPPFILES2=nandsim_manual.c
XBSVFLAGS += -D2 NO_CPP_PORTAL_CODE

include ../../Makefile.xbsv
