
BSVDIR=../../bsv
S2H = PcieTestBenchRequest DmaConfig
H2S = PcieTestBenchIndication DmaIndication
BSVFILES = PcieTestBench.bsv Top.bsv ../../lib/deprecated/DmaUtils.bsv
CPPFILES=testpcie.cpp
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common
