
CONNECTALDIR?=../..
INTERFACES = SignalGenRequest SignalGenIndication \
	BlueScopeEventRequest BlueScopeEventIndication
BSVFILES = SignalGen.bsv Top.bsv
CPPFILES=testbluescopeevent.cpp
#CONNECTALFLAGS=--bscflags " -D TRACE_AXI"

include $(CONNECTALDIR)/Makefile.connectal
