CONNECTALDIR?=../..
S2H_INTERFACES = YuvRequest:YuvIF.request
H2S_INTERFACES = YuvIF:YuvIndication

BSVFILES = YuvIF.bsv
CPPFILES= testyuv.cpp
NUMBER_OF_MASTERS =0

include $(CONNECTALDIR)/Makefile.connectal
