
CONNECTALDIR?=../..
INTERFACES = NandSimRequest NandSimIndication
BSVFILES = NandSim.bsv Top.bsv
CPPFILES=testnandsim_test.cpp
#CPPFILES=testnandsim.cpp
#CPPFILES=nandsim_manual.c

include $(CONNECTALDIR)/Makefile.connectal
