
S2H = NandSimRequest
H2S = NandSimIndication
BSVFILES = ../../lib/bsv/NandSim.bsv Top.bsv ../../lib/bsv/NandSimNames.bsv
CPPFILES=testnandsim.cpp
XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.connectal
