
S2H = SinkRequest
H2S = SinkIndication
BSVFILES = Sink.bsv Top.bsv
CPPFILES=test.cpp
XBSVFLAGS += --bscflags " -D NumberOfMasters=0"
#XBSVFLAGS=--bscflags " -D TRACE_AXI"

include ../../Makefile.common

