
CONNECTALDIR?=../..
INTERFACES = SinkRequest SinkIndication
BSVFILES = Sink.bsv Top.bsv
CPPFILES=test.cpp
NUMBER_OF_MASTERS =0
#CONNECTALFLAGS=--bscflags " -D TRACE_AXI"

include $(CONNECTALDIR)/Makefile.connectal

